#!/bin/sh

currbrows=$(xdg-settings get default-web-browser)
case $currbrows in
	firefox.desktop)
		xdg-settings set default-web-browser com.google.Chrome.desktop
		/usr/bin/notify-send -t 3000 "Google Chrome is now the default browser"
		echo "Google Chrome set as default browser" ;;
	com.google.Chrome.desktop)
		xdg-settings set default-web-browser firefox.desktop
		/usr/bin/notify-send -t 3000 "Firefox is now the default browser"
		echo "Firefox set as default browser" ;;
	*)
		# Fallback: if current browser is neither, set to Firefox
		xdg-settings set default-web-browser firefox.desktop
		/usr/bin/notify-send -t 3000 "Firefox is now the default browser"
		echo "Firefox set as default browser (fallback)" ;;
esac
