#!/bin/bash

# Load webhook URL from ~/.envrc if not already set by direnv
[ -z "$BACKUP_HOOKWEB" ] && . "$HOME/.envrc"
WEBHOOK_URL="$BACKUP_HOOKWEB"

#echo $WEBHOOK_URL

# Replace 'YOUR_MESSAGE' with the message you want to send
MESSAGE="This is a test message. $(date)"
#
## Create the payload for the Discord webhook
PAYLOAD='{"content": "'"$MESSAGE"'"}'
#
## Send the payload to the webhook
curl -X POST -H "Content-Type: application/json" -d "$PAYLOAD" "$WEBHOOK_URL"
