#!/bin/bash

# Replace 'YOUR_WEBHOOK_URL' with the URL of your Discord webhook
WEBHOOK_URL="***REMOVED***"

#echo $WEBHOOK_URL

# Replace 'YOUR_MESSAGE' with the message you want to send
MESSAGE="This is a test message. $(date)"
#
## Create the payload for the Discord webhook
PAYLOAD='{"content": "'"$MESSAGE"'"}'
#
## Send the payload to the webhook
curl -X POST -H "Content-Type: application/json" -d "$PAYLOAD" "$WEBHOOK_URL"
