#!/usr/bin/env bash
set -euo pipefail

#PATHTOIMAGES="/usr/share/backgrounds"
##PATHTOIMAGES=$1
#if [ -d "$PATHTOIMAGES" ];
#then
#    echo -e "Path: ## $PATHTOIMAGES ## exists"
#    randimg=$(find "$PATHTOIMAGES"*/*.* | shuf -n 1)
#    echo "Random image: $randimg"
#    feh --bg-fill "$randimg"
#    betterlockscreen -u "$randimg" -b 1
#    #notify-send -t 2000 "i3fehrb" "Done preparing lockscreen"
#else
#    echo -e "Path: $PATHTOIMAGES\nDOES NOT exist"
#fi

while true; do
	find /usr/share/backgrounds/ -type f \( -name '*.jpg' -o -name '*.png' -o -name '*.jpeg' \) -print0 |
	    shuf -n1 -z | xargs -0 feh --bg-fill
	sleep 15m
done
