#!/bin/bash
echo -e "https://linktr.ee/gimpysticks\nhttps://www.instagram.com/gimpysticks\n https://gimpysticks.redbubble.com\n https://ko-fi.com/gimpysticks\n #midjourney @gimpysticks " | xclip -selection clipboard -i
