#!/usr/bin/env bash

params=$(echo "$*" | sed 's/ /+/g')
duration='&sort=length&datef=week&durf=10min_more'
#echo $params
nordvpn c
# sleep 2
# tmux kill-server
brave-browser --incognito "https://www.xvideos.com/?k=${params}${duration}" &>/dev/null &
mkdir -p /tmp/xvids
tmux new-session -A -s Adult -c /tmp/xvids
