#!/bin/sh
last=$(tail -1 $HOME/.topics)
if command -v wl-copy >/dev/null 2>&1; then
    echo "${last}" | wl-copy
elif command -v xclip >/dev/null 2>&1; then
    echo "${last}" | xclip
fi
echo "${last}"
