#!/bin/bash
TOKEN="894327394:AAHpY2eoebJDhYHWse9-DFvu6xr3fcT2pi8"
CHAT_ID="@gimpysgroup"
URL="https://api.telegram.org/bot$TOKEN/sendMessage"
tmpfile="/home/sticks/backup.tmp"

beginmsg="Test script Started  $(date +%c)"
/usr/bin/notify-send -t 0 "$(echo -e $beginmsg)"
MESSAGE="$(echo -e $beginmsg)" 
curl -s -X POST $URL -d chat_id=$CHAT_ID -d text="$MESSAGE" -o $tmpfile 

endmsg="Test script complete  $(date +%c)"
/usr/bin/notify-send -t 0 "$(echo -e $endmsg)"
MESSAGE="$(echo -e $endmsg)" 
curl -s -X POST $URL -d chat_id=$CHAT_ID -d text="$MESSAGE" -o $tmpfile 
