#!  /bin/bash
if ! [ -e /etc/init.d/cupsys ];then
 DUMMYCUPSYS=1
 ln -s /bin/echo  /etc/init.d/cupsys
fi
if ! [ -e /etc/init.d/cups ];then
 DUMMYCUPS=1
 ln -s /bin/echo  /etc/init.d/cups
fi
if ! [ -e /etc/init.d/lpd ];then
 DUMMYLPD=1
 ln -s /bin/echo  /etc/init.d/lpd
fi
if ! [ -e /etc/init.d/lprng ];then
 DUMMYLPRNG=1
 ln -s /bin/echo  /etc/init.d/lprng
fi
dpkg  -x cupswrapperDCP7020-2.0.1-2.i386.deb /
dpkg  -P    cupswrapperDCP7020
dpkg  -x brdcp7020lpr-2.0.1-1.i386.deb /
dpkg  -P    brdcp7020lpr
if [ "$DUMMYCUPS" = 1 ];then
  lsc=$(ls -al /etc/init.d/cups | grep ^l )
  if [ "$lsc" != "" ];then
    rm /etc/init.d/cups
  fi
fi

if [ "$DUMMYCUPSYS" = 1 ];then
  lsc=$(ls -al /etc/init.d/cupsys | grep ^l )
  if [ "$lsc" != "" ];then
    rm /etc/init.d/cupsys
  fi
fi

if [ "$DUMMYLPD" = 1 ];then
  lsc=$(ls -al /etc/init.d/lpd | grep ^l )
  if [ "$lsc" != "" ];then
    rm /etc/init.d/lpd
  fi
fi

if [ "$DUMMYLPRNG" = 1 ];then
  lsc=$(ls -al /etc/init.d/lprng | grep ^l )
  if [ "$lsc" != "" ];then
    rm /etc/init.d/lprng
  fi
fi
